version: '3'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: are.moe/testtask-server
    restart: on-failure
    env_file: .env
    depends_on:
      - postgres
    networks:
      - backend
      - frontend
    expose:
      - 3000
    ports:
      - ${SERVER_PORT:-3001}:3000
    environment:
      - PORT=3000
      - PGHOST=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=postgres
    logging:
      driver: json-file
      options:
        max-size: 100M

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${MODE:-production}
        - VUE_APP_API_URL=http://localhost:${SERVER_PORT:-3001}/
    image: are.moe/testtask-client
    restart: on-failure
    env_file: .env
    depends_on:
      - server
    networks:
      - frontend
    ports:
      - ${CLIENT_PORT:-3000}:80
    logging:
      driver: json-file
      options:
        max-size: 100M

  postgres:
    image: postgres:16-alpine
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    logging:
      driver: json-file
      options:
        max-size: 100M

volumes:
  data:
    driver: local

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
